version: 2.1

aliases:
  - &environment
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

  - &restore_cache_dependencies
    name: "Restore dependencies from the cache"
    keys:
      - sbt-dependencies-{{ checksum "build.sbt" }}
      # fallback to using the latest cache if no exact match is found
      - sbt-dependencies-

  - &update_dependencies
    name: "Update all the dependencies"
    command: .circleci/hasNotChanged build.sbt && echo "SKIPPING DEPS UPDATE" || cat /dev/null | sbt update +fenek/update +sparkTest/update


  - &save_cache_dependencies
    name: "Save dependencies in the cache"
    paths:
      - ~/.m2
      - ~/.ivy2
      - ~/.sbt
      - ~/.cache
    key: sbt-dependencies-{{ checksum "build.sbt" }}

  - &fmt_check
    name: "Check code format"
    command: cat /dev/null | sbt check

  - &configure_gpg
    name: configure GPG
    command: |
      mkdir -p ~/.gnupg
      echo "charset utf-8" > ~/.gnupg/gpg.conf
      echo "use-agent" >> ~/.gnupg/gpg.conf
      echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
      echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
      chown -R $(whoami) ~/.gnupg/
      find ~/.gnupg -type f -exec chmod 600 {} \;
      find ~/.gnupg -type d -exec chmod 700 {} \;
      echo $SECR_GPG_ASC_BASE64 | base64 --decode | gpg --batch --no-tty --import --yes

  - &only_master
        filters:
            branches:
                ignore: gh-pages

commands:
  build_project:
    description: build a sub-project
    parameters:
      project_name:
        type: string
      extra_fs_deps:
        default:  ""
        type: string
    steps:
      - checkout
      - restore_cache: *restore_cache_dependencies
      - run: *fmt_check
      #- run:
      #    name: check
      #    command: ls -R
      #- run:
      #    name: Compile code and test code << parameters.project_name >>
      #    command: cat /dev/null | sbt << parameters.project_name >>/compile << parameters.project_name >>/test:compile
      - run:
          name: Test and compute code coverage << parameters.project_name >>
          command: bash -x .circleci/hasNotChanged build.sbt << parameters.extra_fs_deps >> << parameters.project_name >> || cat /dev/null | sbt coverage << parameters.project_name >>/test << parameters.project_name >>/coverageReport

  release_all:
    description: release all sub-project
    steps:
      - checkout
      - restore_cache: *restore_cache_dependencies
      - run: *configure_gpg
#      - run:
#          name: Check no staging repo is opened on OSS Sonatype
#          command: |
#            cat /dev/null | sbt sonatypeLog | ((grep "No staging log is found" > /dev/null && echo "No staging repo found. We can deliver. 👍") || (echo "A staging repo has been opened. Another job might be delivering. Drop it! 😈"; sbt sonatypeDrop))
      - run:
          name: Deliver all projects to maven central
          command: |
            cat /dev/null | sbt centrifuge/releaseEarly sparkZio/releaseEarly plumbus/releaseEarly +typedpath/releaseEarly fenek/releaseEarly +sparkTest/releaseEarly


jobs:
  update_deps_in_cache:
    <<: *environment
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: *restore_cache_dependencies
      - run: *fmt_check
      - run: *update_dependencies
      - save_cache: *save_cache_dependencies

  centrifuge:
    <<: *environment
    working_directory: ~/repo
    steps:
      - build_project:
          project_name: centrifuge

  plumbus:
    <<: *environment
    working_directory: ~/repo
    steps:
      - build_project:
          project_name: plumbus

  typedpath:
    <<: *environment
    working_directory: ~/repo
    steps:
      - build_project:
          project_name: typedpath

  fenek:
    <<: *environment
    working_directory: ~/repo
    steps:
      - build_project:
          project_name: fenek
          extra_fs_deps: typedpath

  sparkzio:
    <<: *environment
    working_directory: ~/repo
    steps:
      - build_project:
          project_name: sparkZio
          extra_fs_deps: spark-zio

  sparktest:
    <<: *environment
    working_directory: ~/repo
    steps:
      - build_project:
          project_name: sparkTest
          extra_fs_deps: spark-test

  release:
    <<: *environment
    working_directory: ~/repo
    steps:
      - release_all

  site:
    <<: *environment
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: *restore_cache_dependencies
      - run:
          name: buildSiteOrNot
          command: |
            build() {
              sudo apt-get update
              sudo apt-get install -y ruby ruby-dev
              sudo gem install jekyll
              git config --global user.name "Univalence"
              git config --global user.email "${UNIVALENCE_EMAIL}"
              export SBT_GHPAGES_COMMIT_MESSAGE='publishing microSite [ci skip]'
              cat /dev/null | sbt publishMicrosite
            }
            .circleci/hasNotChanged build.sbt site && echo "skipping build" || build

workflows:
  master:
    jobs:
      - update_deps_in_cache: *only_master
      - centrifuge: *only_master
      - typedpath: *only_master
      - fenek: *only_master
      - plumbus: *only_master
      - sparkzio: *only_master
      - sparktest: *only_master
      - release: *only_master
      - site: *only_master